version: '3'

services:
  api:
    build: './api'
    volumes:
      - ./api:/usr/src/app
    ports:
      - 10010:10010
  app:
    build: './app'
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - api
